[tool.poetry]
name = "Estar do Vale"
version = "0.1.0"
description = ""
authors = ["Paula <paulakaferreira@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
pygame = "^2.5.0"

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"
pyproject-flake8 = "^6.0.0"
black = "^23.7.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
